In [1]:
# import libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from scipy import stats

# nba scraper
from nba_api.stats.endpoints import PlayerAwards
from nba_api.stats.endpoints import PlayerGameLog
from nba_api.stats.endpoints import PlayerIndex
from nba_api.stats.endpoints import playercareerstats

In [2]:
# get nba player data for seasons 2015-2025
# get seasons 2015-2025
seasons = [f'{year}-{str(int(year) + 1)[2:]}' for year in range(2015, 2025)]

player_data = []
for season in seasons:
    player_data.append(PlayerIndex(season=season).get_data_frames()[0])
    # add season to player data
    player_data[-1]['SEASON'] = season

player_data = pd.concat(player_data)

In [3]:
player_data

,PERSON_ID,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,PLAYER_SLUG,TEAM_ID,TEAM_SLUG,IS_DEFUNCT,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,...,DRAFT_ROUND,DRAFT_NUMBER,ROSTER_STATUS,FROM_YEAR,TO_YEAR,PTS,REB,AST,STATS_TIMEFRAME,SEASON
0,203919,Adams,Jordan,jordan-adams,1610612763,grizzlies,0,Memphis,Grizzlies,MEM,...,1.0,22.0,1.0,2014,2015,3.5,1.0,1.5,Season,2015-16
1,1626146,Alexander,Cliff,cliff-alexander,1610612757,blazers,0,Portland,Trail Blazers,POR,...,NaN,NaN,1.0,2015,2015,1.3,0.8,0.0,Season,2015-16
2,200811,Amundson,Lou,lou-amundson,1610612752,knicks,0,New York,Knicks,NYK,...,NaN,NaN,1.0,2006,2015,1.8,1.7,0.4,Season,2015-16
3,2365,Andersen,Chris,chris-andersen,1610612763,grizzlies,0,Memphis,Grizzlies,MEM,...,NaN,NaN,1.0,2001,2016,3.9,3.6,0.4,Season,2015-16
4,202341,Anderson,James,james-anderson,1610612758,kings,0,Sacramento,Kings,SAC,...,1.0,20.0,1.0,2010,2015,3.5,1.7,0.8,Season,2015-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570,1629027,Young,Trae,trae-young,1610612737,hawks,0,Atlanta,Hawks,ATL,...,1.0,5.0,1.0,2018,2024,24.2,3.1,11.6,Season,2024-25
571,1627826,Zubac,Ivica,ivica-zubac,1610612746,clippers,0,LA,Clippers,LAC,...,2.0,32.0,1.0,2016,2024,16.8,12.6,2.7,Season,2024-25
572,1641783,da Silva,Tristan,tristan-da-silva,1610612753,magic,0,Orlando,Magic,ORL,...,1.0,18.0,1.0,2024,2024,7.2,3.3,1.5,Season,2024-25
573,1628427,Čančar,Vlatko,vlatko-čančar,1610612743,nuggets,0,Denver,Nuggets,DEN,...,2.0,49.0,1.0,2019,2024,1.8,2.5,0.7,Season,2024-25
574,203967,Šarić,Dario,dario-šarić,1610612743,nuggets,0,Denver,Nuggets,DEN,...,1.0,12.0,1.0,2016,2024,3.5,3.1,1.4,Season,2024-25

In [4]:
player_data.columns

Index(['PERSON_ID', 'PLAYER_LAST_NAME', 'PLAYER_FIRST_NAME', 'PLAYER_SLUG',
       'TEAM_ID', 'TEAM_SLUG', 'IS_DEFUNCT', 'TEAM_CITY', 'TEAM_NAME',
       'TEAM_ABBREVIATION', 'JERSEY_NUMBER', 'POSITION', 'HEIGHT', 'WEIGHT',
       'COLLEGE', 'COUNTRY', 'DRAFT_YEAR', 'DRAFT_ROUND', 'DRAFT_NUMBER',
       'ROSTER_STATUS', 'FROM_YEAR', 'TO_YEAR', 'PTS', 'REB', 'AST',
       'STATS_TIMEFRAME', 'SEASON'],
      dtype='object')

In [5]:
# Create empty list to store career stats
season_stats = []

# get all unique player ids
unique_player_ids = player_data['PERSON_ID'].unique()

# Loop through each player ID and get their career stats
for player_id in unique_player_ids:
    try:
        # Get career stats for player
        player_stats = playercareerstats.PlayerCareerStats(player_id=player_id)
        # Get the data frame from the response
        stats_df = player_stats.get_data_frames()[0]
        # Append to list
        season_stats.append(stats_df)
    except:
        print(f"Could not get stats for player ID {player_id}")
        continue

# Combine all stats into single dataframe if list is not empty
if season_stats:
    season_stats = pd.concat(season_stats)
else:
    print("No career stats were retrieved")

Could not get stats for player ID 1628778
Could not get stats for player ID 204222
Could not get stats for player ID 1628391
Could not get stats for player ID 200746
Could not get stats for player ID 2546
Could not get stats for player ID 1627853
Could not get stats for player ID 201571
Could not get stats for player ID 1630555
Could not get stats for player ID 1627760
Could not get stats for player ID 1628238
Could not get stats for player ID 203145
Could not get stats for player ID 202357
Could not get stats for player ID 202339
Could not get stats for player ID 1629833
Could not get stats for player ID 1630195
Could not get stats for player ID 1629067
Could not get stats for player ID 202340
Could not get stats for player ID 1629649
Could not get stats for player ID 1629717
Could not get stats for player ID 1628425
Could not get stats for player ID 1630602
Could not get stats for player ID 1629783
Could not get stats for player ID 203504
Could not get stats for player ID 1629719
Could not get stats for player ID 1630267
Could not get stats for player ID 1629962
Could not get stats for player ID 1626161
Could not get stats for player ID 1629958
Could not get stats for player ID 1629185
Could not get stats for player ID 1627737
Could not get stats for player ID 1629109
Could not get stats for player ID 1629076
Could not get stats for player ID 1630536
Could not get stats for player ID 1627822
Could not get stats for player ID 202326
Could not get stats for player ID 1629633
Could not get stats for player ID 1629600
Could not get stats for player ID 202334
Could not get stats for player ID 1629602
Could not get stats for player ID 1630693
Could not get stats for player ID 1629035
Could not get stats for player ID 1630306
Could not get stats for player ID 1629604
Could not get stats for player ID 201961
Could not get stats for player ID 202324
Could not get stats for player ID 1630238
Could not get stats for player ID 1627854
Could not get stats for player ID 1630758
Could not get stats for player ID 1628982
Could not get stats for player ID 1629164
Could not get stats for player ID 1629755
Could not get stats for player ID 1629788
Could not get stats for player ID 203090
Could not get stats for player ID 1629607
Could not get stats for player ID 1630565
Could not get stats for player ID 1627823
Could not get stats for player ID 203918
Could not get stats for player ID 203816
Could not get stats for player ID 2730
Could not get stats for player ID 1630210
Could not get stats for player ID 1630190
Could not get stats for player ID 1630624
Could not get stats for player ID 201586
Could not get stats for player ID 1628402
Could not get stats for player ID 1628367
Could not get stats for player ID 1630525
Could not get stats for player ID 1626169
Could not get stats for player ID 1630686
Could not get stats for player ID 1629083
Could not get stats for player ID 203087
Could not get stats for player ID 1627774
Could not get stats for player ID 1630575
Could not get stats for player ID 1629712
Could not get stats for player ID 1630994
Could not get stats for player ID 1627789
Could not get stats for player ID 1629751
Could not get stats for player ID 1630787
Could not get stats for player ID 1630605
Could not get stats for player ID 203463
Could not get stats for player ID 200794
Could not get stats for player ID 202328
Could not get stats for player ID 1629752
Could not get stats for player ID 1628539
Could not get stats for player ID 1630278
Could not get stats for player ID 1630612
Could not get stats for player ID 1629005
Could not get stats for player ID 203457
Could not get stats for player ID 1628021
Could not get stats for player ID 1628419
Could not get stats for player ID 1629873
Could not get stats for player ID 1629309
Could not get stats for player ID 1630698
Could not get stats for player ID 1629672
Could not get stats for player ID 1630691
Could not get stats for player ID 1629641
Could not get stats for player ID 202722
Could not get stats for player ID 201976
Could not get stats for player ID 1630180
Could not get stats for player ID 1641931
Could not get stats for player ID 1641778
Could not get stats for player ID 1631205
Could not get stats for player ID 202711
Could not get stats for player ID 1629716
Could not get stats for player ID 1629052
Could not get stats for player ID 1631167
Could not get stats for player ID 1631112
Could not get stats for player ID 1629650
Could not get stats for player ID 1630535
Could not get stats for player ID 1629718
Could not get stats for player ID 1628972
Could not get stats for player ID 203493
Could not get stats for player ID 1630618
Could not get stats for player ID 1630608
Could not get stats for player ID 203496
Could not get stats for player ID 1630622
Could not get stats for player ID 1631098
Could not get stats for player ID 1641926
Could not get stats for player ID 1629603
Could not get stats for player ID 1630929
Could not get stats for player ID 1630537
Could not get stats for player ID 1628981
Could not get stats for player ID 1630201
Could not get stats for player ID 1630259
Could not get stats for player ID 1630235
Could not get stats for player ID 203095
Could not get stats for player ID 1631241
Could not get stats for player ID 1641788
Could not get stats for player ID 1641847
Could not get stats for player ID 201568
Could not get stats for player ID 1641945
Could not get stats for player ID 1630586
Could not get stats for player ID 1629232
Could not get stats for player ID 1628385
Could not get stats for player ID 1631367
Could not get stats for player ID 1628984
Could not get stats for player ID 1630564
Could not get stats for player ID 1631100
Could not get stats for player ID 1631338
Could not get stats for player ID 1630204
Could not get stats for player ID 1630284
Could not get stats for player ID 202330
Could not get stats for player ID 1630207
Could not get stats for player ID 1641793
Could not get stats for player ID 203200
Could not get stats for player ID 1630562
Could not get stats for player ID 202704
Could not get stats for player ID 1630610
Could not get stats for player ID 1641749
Could not get stats for player ID 1627745
Could not get stats for player ID 1630240
Could not get stats for player ID 1630184
Could not get stats for player ID 1629642
Could not get stats for player ID 1631254
Could not get stats for player ID 1641754
Could not get stats for player ID 1626246
Could not get stats for player ID 202083
Could not get stats for player ID 1630219
Could not get stats for player ID 1629667
Could not get stats for player ID 201580
Could not get stats for player ID 1641877
Could not get stats for player ID 1629002
Could not get stats for player ID 1630600
Could not get stats for player ID 1629875
Could not get stats for player ID 202694
Could not get stats for player ID 203488
Could not get stats for player ID 1630227
Could not get stats for player ID 1641806
Could not get stats for player ID 1629670
Could not get stats for player ID 1630647
Could not get stats for player ID 1626224
Could not get stats for player ID 1641970
Could not get stats for player ID 1630196
Could not get stats for player ID 1630197
Could not get stats for player ID 1630554
Could not get stats for player ID 1629629
Could not get stats for player ID 1626196
Could not get stats for player ID 1629010
Could not get stats for player ID 1631115
Could not get stats for player ID 201565
Could not get stats for player ID 1630346
Could not get stats for player ID 1629677
Could not get stats for player ID 1631257
Could not get stats for player ID 1641766
Could not get stats for player ID 1630846
Could not get stats for player ID 1629678
Could not get stats for player ID 1631220
Could not get stats for player ID 1630285
Could not get stats for player ID 1631376
Could not get stats for player ID 1641771
Could not get stats for player ID 1631173
Could not get stats for player ID 1628372
Could not get stats for player ID 1631306
Could not get stats for player ID 1628464
Could not get stats for player ID 202738
Could not get stats for player ID 1628426
Could not get stats for player ID 1630688
Could not get stats for player ID 203933
Could not get stats for player ID 1629139
Could not get stats for player ID 1631214
Could not get stats for player ID 1642013
Could not get stats for player ID 1629685
Could not get stats for player ID 1630164
Could not get stats for player ID 1631209
Could not get stats for player ID 1626174
Could not get stats for player ID 201152
Could not get stats for player ID 1630209
Could not get stats for player ID 203469
Could not get stats for player ID 1630173
Could not get stats for player ID 203500
Could not get stats for player ID 1628389
Could not get stats for player ID 1631116
Could not get stats for player ID 1630163
Could not get stats for player ID 1628366
Could not get stats for player ID 1631094
Could not get stats for player ID 1629048
Could not get stats for player ID 202687
Could not get stats for player ID 1641710
Could not get stats for player ID 203992
Could not get stats for player ID 1629626
Could not get stats for player ID 1641737
Could not get stats for player ID 1626164
Could not get stats for player ID 1630527
Could not get stats for player ID 1628449
Could not get stats for player ID 1631123
Could not get stats for player ID 1628396
Could not get stats for player ID 1631103
Could not get stats for player ID 1631128
Could not get stats for player ID 1641779
Could not get stats for player ID 1628969
Could not get stats for player ID 1628970
Could not get stats for player ID 1628976
Could not get stats for player ID 1627936
Could not get stats for player ID 1642264
Could not get stats for player ID 1630658
Could not get stats for player ID 1630577
Could not get stats for player ID 1641879
Could not get stats for player ID 1628380
Could not get stats for player ID 201144
Could not get stats for player ID 1626192
Could not get stats for player ID 1641731
Could not get stats for player ID 1641741
Could not get stats for player ID 1628470
Could not get stats for player ID 1642384
Could not get stats for player ID 203109
Could not get stats for player ID 1630595
Could not get stats for player ID 203552
Could not get stats for player ID 201939
Could not get stats for player ID 1642359
Could not get stats for player ID 1630700
Could not get stats for player ID 1642368
Could not get stats for player ID 203954
Could not get stats for player ID 1630623
Could not get stats for player ID 1629234
Could not get stats for player ID 1641787
Could not get stats for player ID 203957
Could not get stats for player ID 1630264
Could not get stats for player ID 1631221
Could not get stats for player ID 203497
Could not get stats for player ID 1630692
Could not get stats for player ID 203932
Could not get stats for player ID 201569
Could not get stats for player ID 1641789
Could not get stats for player ID 203924
Could not get stats for player ID 1631260
Could not get stats for player ID 203110
Could not get stats for player ID 1630224
Could not get stats for player ID 1629750
Could not get stats for player ID 201145
Could not get stats for player ID 1630182
Could not get stats for player ID 1629656
Could not get stats for player ID 1631243
Could not get stats for player ID 1629060
Could not get stats for player ID 1630169
Could not get stats for player ID 1642358
Could not get stats for player ID 1629661
Could not get stats for player ID 1630296
Could not get stats for player ID 1630557
Could not get stats for player ID 1628467
Could not get stats for player ID 1641752
Could not get stats for player ID 1642261
Could not get stats for player ID 1628995
Could not get stats for player ID 1642278
Could not get stats for player ID 1631132
Could not get stats for player ID 1629723
Could not get stats for player ID 1628436
Could not get stats for player ID 1630249
Could not get stats for player ID 1630228
Could not get stats for player ID 1628398
Could not get stats for player ID 1631222
Could not get stats for player ID 203897
Could not get stats for player ID 1629111
Could not get stats for player ID 1641796
Could not get stats for player ID 1630639
Could not get stats for player ID 1627747
Could not get stats for player ID 1627814
Could not get stats for player ID 1628997
Could not get stats for player ID 203926
Could not get stats for player ID 1631121
Could not get stats for player ID 1629162
Could not get stats for player ID 1629098
Could not get stats for player ID 1629001
Could not get stats for player ID 1630241
Could not get stats for player ID 203995
Could not get stats for player ID 203114
Could not get stats for player ID 1641706
Could not get stats for player ID 1641801
Could not get stats for player ID 1641757
Could not get stats for player ID 1631159
Could not get stats for player ID 201988
Could not get stats for player ID 1629003
Could not get stats for player ID 1631303
Could not get stats for player ID 1642434
Could not get stats for player ID 1631169
Could not get stats for player ID 1642274
Could not get stats for player ID 1642349
Could not get stats for player ID 203994
Could not get stats for player ID 1630590
Could not get stats for player ID 1631342
Could not get stats for player ID 203486
Could not get stats for player ID 1641764
Could not get stats for player ID 1627751
Could not get stats for player ID 1629673
Could not get stats for player ID 1641854
Could not get stats for player ID 1629645
Could not get stats for player ID 1629008
Could not get stats for player ID 1626171
Could not get stats for player ID 204001
Could not get stats for player ID 1642366
Could not get stats for player ID 1630695
Could not get stats for player ID 203939
Could not get stats for player ID 1626181
Could not get stats for player ID 1627752
Could not get stats for player ID 1630202
Could not get stats for player ID 1641765
Could not get stats for player ID 1642389
Could not get stats for player ID 1630243
Could not get stats for player ID 202691
Could not get stats for player ID 1629731
Could not get stats for player ID 1630532
Could not get stats for player ID 1629021
Could not get stats for player ID 1631133
Could not get stats for player ID 1641716
Could not get stats for player ID 1629022
Could not get stats for player ID 1641717
Could not get stats for player ID 1630811
Could not get stats for player ID 1641775
Could not get stats for player ID 1642266
Could not get stats for player ID 1642276
Could not get stats for player ID 1629023
Could not get stats for player ID 1631102
Could not get stats for player ID 1630322
Could not get stats for player ID 1630570
Could not get stats for player ID 1641817
Could not get stats for player ID 1631212
Could not get stats for player ID 1642377
Could not get stats for player ID 1641705

C:\Users\17782\AppData\Local\Temp\ipykernel_9376\555173704.py:22: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  season_stats = pd.concat(season_stats)

In [21]:
season_stats

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203919,2014-15,00,1610612763,MEM,20.0,30,0,248.0,35,...,0.609,9,19,28,16,16,7,14,24,94
1,203919,2015-16,00,1610612763,MEM,21.0,2,0,15.0,2,...,0.600,0,2,2,3,3,0,2,2,7
0,1626146,2015-16,00,1610612757,POR,20.0,8,0,36.0,5,...,0.000,2,4,6,0,1,2,1,1,10
0,200811,2006-07,00,1610612762,UTA,24.0,1,0,2.0,0,...,0.000,0,0,0,0,0,0,0,0,0
1,200811,2006-07,00,1610612755,PHI,24.0,10,0,87.0,6,...,0.400,13,15,28,1,1,8,5,15,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,203967,2022-23,00,1610612756,PHX,29.0,37,12,533.0,76,...,0.818,39,103,142,57,13,5,36,69,215
8,203967,2022-23,00,1610612760,OKC,29.0,20,0,273.0,51,...,0.844,14,51,65,17,7,2,19,30,147
9,203967,2022-23,00,0,TOT,29.0,57,12,806.0,127,...,0.829,53,154,207,74,20,7,55,99,362
10,203967,2023-24,00,1610612744,GSW,30.0,64,9,1098.0,181,...,0.849,73,210,283,144,31,10,78,112,515
11,203967,2024-25,00,1610612743,DEN,31.0,16,4,210.0,21,...,0.700,14,36,50,23,7,1,15,19,56

In [47]:
player_data_totals=player_data.merge(season_stats, left_on='PERSON_ID', right_on='PLAYER_ID', how='right')
player_data_totals

,PERSON_ID,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,PLAYER_SLUG,TEAM_ID_x,TEAM_SLUG,IS_DEFUNCT,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION_x,...,FT_PCT,OREB,DREB,REB_y,AST_y,STL,BLK,TOV,PF,PTS_y
0,203919,Adams,Jordan,jordan-adams,1610612763,grizzlies,0,Memphis,Grizzlies,MEM,...,0.609,9,19,28,16,16,7,14,24,94
1,203919,Adams,Jordan,jordan-adams,1610612763,grizzlies,0,Memphis,Grizzlies,MEM,...,0.600,0,2,2,3,3,0,2,2,7
2,1626146,Alexander,Cliff,cliff-alexander,1610612757,blazers,0,Portland,Trail Blazers,POR,...,0.000,2,4,6,0,1,2,1,1,10
3,200811,Amundson,Lou,lou-amundson,1610612752,knicks,0,New York,Knicks,NYK,...,0.000,0,0,0,0,0,0,0,0,0
4,200811,Amundson,Lou,lou-amundson,1610612752,knicks,0,New York,Knicks,NYK,...,0.400,13,15,28,1,1,8,5,15,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8876,203967,Šarić,Dario,dario-šarić,1610612743,nuggets,0,Denver,Nuggets,DEN,...,0.818,39,103,142,57,13,5,36,69,215
8877,203967,Šarić,Dario,dario-šarić,1610612743,nuggets,0,Denver,Nuggets,DEN,...,0.844,14,51,65,17,7,2,19,30,147
8878,203967,Šarić,Dario,dario-šarić,1610612743,nuggets,0,Denver,Nuggets,DEN,...,0.829,53,154,207,74,20,7,55,99,362
8879,203967,Šarić,Dario,dario-šarić,1610612743,nuggets,0,Denver,Nuggets,DEN,...,0.849,73,210,283,144,31,10,78,112,515
8880,203967,Šarić,Dario,dario-šarić,1610612743,nuggets,0,Denver,Nuggets,DEN,...,0.700,14,36,50,23,7,1,15,19,56

In [48]:
player_data_totals.columns

Index(['PERSON_ID', 'PLAYER_LAST_NAME', 'PLAYER_FIRST_NAME', 'PLAYER_SLUG',
       'TEAM_ID_x', 'TEAM_SLUG', 'IS_DEFUNCT', 'TEAM_CITY', 'TEAM_NAME',
       'TEAM_ABBREVIATION_x', 'JERSEY_NUMBER', 'POSITION', 'HEIGHT', 'WEIGHT',
       'COLLEGE', 'COUNTRY', 'DRAFT_YEAR', 'DRAFT_ROUND', 'DRAFT_NUMBER',
       'ROSTER_STATUS', 'FROM_YEAR', 'TO_YEAR', 'PTS_x', 'REB_x', 'AST_x',
       'STATS_TIMEFRAME', 'SEASON', 'PLAYER_ID', 'SEASON_ID', 'LEAGUE_ID',
       'TEAM_ID_y', 'TEAM_ABBREVIATION_y', 'PLAYER_AGE', 'GP', 'GS', 'MIN',
       'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',
       'FT_PCT', 'OREB', 'DREB', 'REB_y', 'AST_y', 'STL', 'BLK', 'TOV', 'PF',
       'PTS_y'],
      dtype='object')

In [49]:
player_data_totals=player_data_totals.drop(columns=['LEAGUE_ID', 'TEAM_ID_x','TEAM_ABBREVIATION_x','PTS_x','AST_x','REB_x'])
player_data_totals

,PERSON_ID,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,PLAYER_SLUG,TEAM_SLUG,IS_DEFUNCT,TEAM_CITY,TEAM_NAME,JERSEY_NUMBER,POSITION,...,FT_PCT,OREB,DREB,REB_y,AST_y,STL,BLK,TOV,PF,PTS_y
0,203919,Adams,Jordan,jordan-adams,grizzlies,0,Memphis,Grizzlies,3,G,...,0.609,9,19,28,16,16,7,14,24,94
1,203919,Adams,Jordan,jordan-adams,grizzlies,0,Memphis,Grizzlies,3,G,...,0.600,0,2,2,3,3,0,2,2,7
2,1626146,Alexander,Cliff,cliff-alexander,blazers,0,Portland,Trail Blazers,34,F,...,0.000,2,4,6,0,1,2,1,1,10
3,200811,Amundson,Lou,lou-amundson,knicks,0,New York,Knicks,17,F,...,0.000,0,0,0,0,0,0,0,0,0
4,200811,Amundson,Lou,lou-amundson,knicks,0,New York,Knicks,17,F,...,0.400,13,15,28,1,1,8,5,15,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8876,203967,Šarić,Dario,dario-šarić,nuggets,0,Denver,Nuggets,9,F-C,...,0.818,39,103,142,57,13,5,36,69,215
8877,203967,Šarić,Dario,dario-šarić,nuggets,0,Denver,Nuggets,9,F-C,...,0.844,14,51,65,17,7,2,19,30,147
8878,203967,Šarić,Dario,dario-šarić,nuggets,0,Denver,Nuggets,9,F-C,...,0.829,53,154,207,74,20,7,55,99,362
8879,203967,Šarić,Dario,dario-šarić,nuggets,0,Denver,Nuggets,9,F-C,...,0.849,73,210,283,144,31,10,78,112,515
8880,203967,Šarić,Dario,dario-šarić,nuggets,0,Denver,Nuggets,9,F-C,...,0.700,14,36,50,23,7,1,15,19,56

In [50]:
# show nans
player_data_totals.isna().sum()

PERSON_ID                 0
PLAYER_LAST_NAME          0
PLAYER_FIRST_NAME         0
PLAYER_SLUG               0
TEAM_SLUG              1625
IS_DEFUNCT                0
TEAM_CITY              1625
TEAM_NAME              1625
JERSEY_NUMBER          1630
POSITION                  0
HEIGHT                    0
WEIGHT                    1
COLLEGE                   0
COUNTRY                   0
DRAFT_YEAR             1666
DRAFT_ROUND            1775
DRAFT_NUMBER           1786
ROSTER_STATUS          1625
FROM_YEAR                 0
TO_YEAR                   0
STATS_TIMEFRAME           0
SEASON                    0
PLAYER_ID                 0
SEASON_ID                 0
TEAM_ID_y                 0
TEAM_ABBREVIATION_y       0
PLAYER_AGE                0
GP                        0
GS                        0
MIN                       0
FGM                       0
FGA                       0
FG_PCT                    0
FG3M                      0
FG3A                      0
FG3_PCT                   0
FTM                       0
FTA                       0
FT_PCT                    0
OREB                      0
DREB                      0
REB_y                     0
AST_y                     0
STL                       0
BLK                       0
TOV                       0
PF                        0
PTS_y                     0
dtype: int64

In [51]:
player_data_totals.columns

Index(['PERSON_ID', 'PLAYER_LAST_NAME', 'PLAYER_FIRST_NAME', 'PLAYER_SLUG',
       'TEAM_SLUG', 'IS_DEFUNCT', 'TEAM_CITY', 'TEAM_NAME', 'JERSEY_NUMBER',
       'POSITION', 'HEIGHT', 'WEIGHT', 'COLLEGE', 'COUNTRY', 'DRAFT_YEAR',
       'DRAFT_ROUND', 'DRAFT_NUMBER', 'ROSTER_STATUS', 'FROM_YEAR', 'TO_YEAR',
       'STATS_TIMEFRAME', 'SEASON', 'PLAYER_ID', 'SEASON_ID', 'TEAM_ID_y',
       'TEAM_ABBREVIATION_y', 'PLAYER_AGE', 'GP', 'GS', 'MIN', 'FGM', 'FGA',
       'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB',
       'DREB', 'REB_y', 'AST_y', 'STL', 'BLK', 'TOV', 'PF', 'PTS_y'],
      dtype='object')

In [52]:
# remove the suffix to columns with _y
player_data_totals.columns = player_data_totals.columns.str.rstrip('_y')
player_data_totals.columns

Index(['PERSON_ID', 'PLAYER_LAST_NAME', 'PLAYER_FIRST_NAME', 'PLAYER_SLUG',
       'TEAM_SLUG', 'IS_DEFUNCT', 'TEAM_CITY', 'TEAM_NAME', 'JERSEY_NUMBER',
       'POSITION', 'HEIGHT', 'WEIGHT', 'COLLEGE', 'COUNTRY', 'DRAFT_YEAR',
       'DRAFT_ROUND', 'DRAFT_NUMBER', 'ROSTER_STATUS', 'FROM_YEAR', 'TO_YEAR',
       'STATS_TIMEFRAME', 'SEASON', 'PLAYER_ID', 'SEASON_ID', 'TEAM_ID',
       'TEAM_ABBREVIATION', 'PLAYER_AGE', 'GP', 'GS', 'MIN', 'FGM', 'FGA',
       'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB',
       'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [53]:
# show nan summary
player_data_totals.isna().sum()

PERSON_ID               0
PLAYER_LAST_NAME        0
PLAYER_FIRST_NAME       0
PLAYER_SLUG             0
TEAM_SLUG            1625
IS_DEFUNCT              0
TEAM_CITY            1625
TEAM_NAME            1625
JERSEY_NUMBER        1630
POSITION                0
HEIGHT                  0
WEIGHT                  1
COLLEGE                 0
COUNTRY                 0
DRAFT_YEAR           1666
DRAFT_ROUND          1775
DRAFT_NUMBER         1786
ROSTER_STATUS        1625
FROM_YEAR               0
TO_YEAR                 0
STATS_TIMEFRAME         0
SEASON                  0
PLAYER_ID               0
SEASON_ID               0
TEAM_ID                 0
TEAM_ABBREVIATION       0
PLAYER_AGE              0
GP                      0
GS                      0
MIN                     0
FGM                     0
FGA                     0
FG_PCT                  0
FG3M                    0
FG3A                    0
FG3_PCT                 0
FTM                     0
FTA                     0
FT_PCT                  0
OREB                    0
DREB                    0
REB                     0
AST                     0
STL                     0
BLK                     0
TOV                     0
PF                      0
PTS                     0
dtype: int64

In [54]:
# remove players where team slug is nan
player_data_totals=player_data_totals[player_data_totals['TEAM_SLUG'].notna()]
player_data_totals

,PERSON_ID,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,PLAYER_SLUG,TEAM_SLUG,IS_DEFUNCT,TEAM_CITY,TEAM_NAME,JERSEY_NUMBER,POSITION,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203919,Adams,Jordan,jordan-adams,grizzlies,0,Memphis,Grizzlies,3,G,...,0.609,9,19,28,16,16,7,14,24,94
1,203919,Adams,Jordan,jordan-adams,grizzlies,0,Memphis,Grizzlies,3,G,...,0.600,0,2,2,3,3,0,2,2,7
2,1626146,Alexander,Cliff,cliff-alexander,blazers,0,Portland,Trail Blazers,34,F,...,0.000,2,4,6,0,1,2,1,1,10
3,200811,Amundson,Lou,lou-amundson,knicks,0,New York,Knicks,17,F,...,0.000,0,0,0,0,0,0,0,0,0
4,200811,Amundson,Lou,lou-amundson,knicks,0,New York,Knicks,17,F,...,0.400,13,15,28,1,1,8,5,15,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8876,203967,Šarić,Dario,dario-šarić,nuggets,0,Denver,Nuggets,9,F-C,...,0.818,39,103,142,57,13,5,36,69,215
8877,203967,Šarić,Dario,dario-šarić,nuggets,0,Denver,Nuggets,9,F-C,...,0.844,14,51,65,17,7,2,19,30,147
8878,203967,Šarić,Dario,dario-šarić,nuggets,0,Denver,Nuggets,9,F-C,...,0.829,53,154,207,74,20,7,55,99,362
8879,203967,Šarić,Dario,dario-šarić,nuggets,0,Denver,Nuggets,9,F-C,...,0.849,73,210,283,144,31,10,78,112,515
8880,203967,Šarić,Dario,dario-šarić,nuggets,0,Denver,Nuggets,9,F-C,...,0.700,14,36,50,23,7,1,15,19,56

In [55]:
# show summary of nan
player_data_totals.isna().sum()

PERSON_ID               0
PLAYER_LAST_NAME        0
PLAYER_FIRST_NAME       0
PLAYER_SLUG             0
TEAM_SLUG               0
IS_DEFUNCT              0
TEAM_CITY               0
TEAM_NAME               0
JERSEY_NUMBER           5
POSITION                0
HEIGHT                  0
WEIGHT                  1
COLLEGE                 0
COUNTRY                 0
DRAFT_YEAR           1240
DRAFT_ROUND          1303
DRAFT_NUMBER         1313
ROSTER_STATUS           0
FROM_YEAR               0
TO_YEAR                 0
STATS_TIMEFRAME         0
SEASON                  0
PLAYER_ID               0
SEASON_ID               0
TEAM_ID                 0
TEAM_ABBREVIATION       0
PLAYER_AGE              0
GP                      0
GS                      0
MIN                     0
FGM                     0
FGA                     0
FG_PCT                  0
FG3M                    0
FG3A                    0
FG3_PCT                 0
FTM                     0
FTA                     0
FT_PCT                  0
OREB                    0
DREB                    0
REB                     0
AST                     0
STL                     0
BLK                     0
TOV                     0
PF                      0
PTS                     0
dtype: int64

In [56]:
# remove players where JERSEY_NUMBER is nan
player_data_totals=player_data_totals[player_data_totals['JERSEY_NUMBER'].notna()]

# show summary of nan
player_data_totals.isna().sum()

PERSON_ID               0
PLAYER_LAST_NAME        0
PLAYER_FIRST_NAME       0
PLAYER_SLUG             0
TEAM_SLUG               0
IS_DEFUNCT              0
TEAM_CITY               0
TEAM_NAME               0
JERSEY_NUMBER           0
POSITION                0
HEIGHT                  0
WEIGHT                  1
COLLEGE                 0
COUNTRY                 0
DRAFT_YEAR           1235
DRAFT_ROUND          1298
DRAFT_NUMBER         1308
ROSTER_STATUS           0
FROM_YEAR               0
TO_YEAR                 0
STATS_TIMEFRAME         0
SEASON                  0
PLAYER_ID               0
SEASON_ID               0
TEAM_ID                 0
TEAM_ABBREVIATION       0
PLAYER_AGE              0
GP                      0
GS                      0
MIN                     0
FGM                     0
FGA                     0
FG_PCT                  0
FG3M                    0
FG3A                    0
FG3_PCT                 0
FTM                     0
FTA                     0
FT_PCT                  0
OREB                    0
DREB                    0
REB                     0
AST                     0
STL                     0
BLK                     0
TOV                     0
PF                      0
PTS                     0
dtype: int64

In [57]:
# remove players where weight is nan
player_data_totals=player_data_totals[player_data_totals['WEIGHT'].notna()]

In [58]:
# show summary of nan
player_data_totals.isna().sum()

PERSON_ID               0
PLAYER_LAST_NAME        0
PLAYER_FIRST_NAME       0
PLAYER_SLUG             0
TEAM_SLUG               0
IS_DEFUNCT              0
TEAM_CITY               0
TEAM_NAME               0
JERSEY_NUMBER           0
POSITION                0
HEIGHT                  0
WEIGHT                  0
COLLEGE                 0
COUNTRY                 0
DRAFT_YEAR           1234
DRAFT_ROUND          1297
DRAFT_NUMBER         1307
ROSTER_STATUS           0
FROM_YEAR               0
TO_YEAR                 0
STATS_TIMEFRAME         0
SEASON                  0
PLAYER_ID               0
SEASON_ID               0
TEAM_ID                 0
TEAM_ABBREVIATION       0
PLAYER_AGE              0
GP                      0
GS                      0
MIN                     0
FGM                     0
FGA                     0
FG_PCT                  0
FG3M                    0
FG3A                    0
FG3_PCT                 0
FTM                     0
FTA                     0
FT_PCT                  0
OREB                    0
DREB                    0
REB                     0
AST                     0
STL                     0
BLK                     0
TOV                     0
PF                      0
PTS                     0
dtype: int64

In [59]:
# show players where DRAFT_YEAR is nan
player_data_totals[player_data_totals['DRAFT_YEAR'].isna()]

,PERSON_ID,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,PLAYER_SLUG,TEAM_SLUG,IS_DEFUNCT,TEAM_CITY,TEAM_NAME,JERSEY_NUMBER,POSITION,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
2,1626146,Alexander,Cliff,cliff-alexander,blazers,0,Portland,Trail Blazers,34,F,...,0.000,2,4,6,0,1,2,1,1,10
3,200811,Amundson,Lou,lou-amundson,knicks,0,New York,Knicks,17,F,...,0.000,0,0,0,0,0,0,0,0,0
4,200811,Amundson,Lou,lou-amundson,knicks,0,New York,Knicks,17,F,...,0.400,13,15,28,1,1,8,5,15,16
5,200811,Amundson,Lou,lou-amundson,knicks,0,New York,Knicks,17,F,...,0.400,13,15,28,1,1,8,5,15,16
6,200811,Amundson,Lou,lou-amundson,knicks,0,New York,Knicks,17,F,...,0.286,7,5,12,0,1,1,2,13,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8789,1629026,Williams,Kenrich,kenrich-williams,thunder,0,Oklahoma City,Thunder,34,G-F,...,0.718,65,176,241,97,43,10,39,110,436
8793,1631466,Williams,Nate,nate-williams,rockets,0,Houston,Rockets,19,G,...,0.667,10,5,15,10,3,2,4,13,53
8794,1631466,Williams,Nate,nate-williams,rockets,0,Houston,Rockets,19,G,...,0.538,12,11,23,7,4,1,4,10,63
8795,1631466,Williams,Nate,nate-williams,rockets,0,Houston,Rockets,19,G,...,0.625,5,8,13,9,8,4,14,16,65
8844,1642443,Young,Jahmir,jahmir-young,bulls,0,Chicago,Bulls,11,G,...,1.000,1,2,3,6,0,0,1,2,11

In [60]:
# remove players with unknown draft year
player_data_totals=player_data_totals[player_data_totals['DRAFT_YEAR'].notna()]

# show summary of nan
player_data_totals.isna().sum()

PERSON_ID             0
PLAYER_LAST_NAME      0
PLAYER_FIRST_NAME     0
PLAYER_SLUG           0
TEAM_SLUG             0
IS_DEFUNCT            0
TEAM_CITY             0
TEAM_NAME             0
JERSEY_NUMBER         0
POSITION              0
HEIGHT                0
WEIGHT                0
COLLEGE               0
COUNTRY               0
DRAFT_YEAR            0
DRAFT_ROUND          63
DRAFT_NUMBER         73
ROSTER_STATUS         0
FROM_YEAR             0
TO_YEAR               0
STATS_TIMEFRAME       0
SEASON                0
PLAYER_ID             0
SEASON_ID             0
TEAM_ID               0
TEAM_ABBREVIATION     0
PLAYER_AGE            0
GP                    0
GS                    0
MIN                   0
FGM                   0
FGA                   0
FG_PCT                0
FG3M                  0
FG3A                  0
FG3_PCT               0
FTM                   0
FTA                   0
FT_PCT                0
OREB                  0
DREB                  0
REB                   0
AST                   0
STL                   0
BLK                   0
TOV                   0
PF                    0
PTS                   0
dtype: int64

In [61]:
# change players where DRAFT_ROUND is nan to 'Undrafted'
player_data_totals.loc[player_data_totals['DRAFT_ROUND'].isna(), 'DRAFT_ROUND'] = 'Undrafted'

# do the same for DRAFT_NUMBER
player_data_totals.loc[player_data_totals['DRAFT_NUMBER'].isna(), 'DRAFT_NUMBER'] = 'Undrafted'

player_data_totals

C:\Users\17782\AppData\Local\Temp\ipykernel_9376\508266427.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Undrafted' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  player_data_totals.loc[player_data_totals['DRAFT_ROUND'].isna(), 'DRAFT_ROUND'] = 'Undrafted'
C:\Users\17782\AppData\Local\Temp\ipykernel_9376\508266427.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Undrafted' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  player_data_totals.loc[player_data_totals['DRAFT_NUMBER'].isna(), 'DRAFT_NUMBER'] = 'Undrafted'

,PERSON_ID,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,PLAYER_SLUG,TEAM_SLUG,IS_DEFUNCT,TEAM_CITY,TEAM_NAME,JERSEY_NUMBER,POSITION,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203919,Adams,Jordan,jordan-adams,grizzlies,0,Memphis,Grizzlies,3,G,...,0.609,9,19,28,16,16,7,14,24,94
1,203919,Adams,Jordan,jordan-adams,grizzlies,0,Memphis,Grizzlies,3,G,...,0.600,0,2,2,3,3,0,2,2,7
56,202341,Anderson,James,james-anderson,kings,0,Sacramento,Kings,5,G-F,...,0.778,2,21,23,18,3,6,13,24,94
57,202341,Anderson,James,james-anderson,kings,0,Sacramento,Kings,5,G-F,...,0.750,16,63,79,41,8,2,30,35,190
58,202341,Anderson,James,james-anderson,kings,0,Sacramento,Kings,5,G-F,...,0.778,3,11,14,9,3,2,7,7,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8876,203967,Šarić,Dario,dario-šarić,nuggets,0,Denver,Nuggets,9,F-C,...,0.818,39,103,142,57,13,5,36,69,215
8877,203967,Šarić,Dario,dario-šarić,nuggets,0,Denver,Nuggets,9,F-C,...,0.844,14,51,65,17,7,2,19,30,147
8878,203967,Šarić,Dario,dario-šarić,nuggets,0,Denver,Nuggets,9,F-C,...,0.829,53,154,207,74,20,7,55,99,362
8879,203967,Šarić,Dario,dario-šarić,nuggets,0,Denver,Nuggets,9,F-C,...,0.849,73,210,283,144,31,10,78,112,515
8880,203967,Šarić,Dario,dario-šarić,nuggets,0,Denver,Nuggets,9,F-C,...,0.700,14,36,50,23,7,1,15,19,56

In [62]:
# show all columns
player_data_totals.columns

Index(['PERSON_ID', 'PLAYER_LAST_NAME', 'PLAYER_FIRST_NAME', 'PLAYER_SLUG',
       'TEAM_SLUG', 'IS_DEFUNCT', 'TEAM_CITY', 'TEAM_NAME', 'JERSEY_NUMBER',
       'POSITION', 'HEIGHT', 'WEIGHT', 'COLLEGE', 'COUNTRY', 'DRAFT_YEAR',
       'DRAFT_ROUND', 'DRAFT_NUMBER', 'ROSTER_STATUS', 'FROM_YEAR', 'TO_YEAR',
       'STATS_TIMEFRAME', 'SEASON', 'PLAYER_ID', 'SEASON_ID', 'TEAM_ID',
       'TEAM_ABBREVIATION', 'PLAYER_AGE', 'GP', 'GS', 'MIN', 'FGM', 'FGA',
       'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB',
       'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [63]:
# get season averages
player_data_totals['PPG'] = player_data_totals['PTS'] / player_data_totals['GP']
player_data_totals['RPG'] = player_data_totals['REB'] / player_data_totals['GP']
player_data_totals['APG'] = player_data_totals['AST'] / player_data_totals['GP']
player_data_totals['SPG'] = player_data_totals['STL'] / player_data_totals['GP']
player_data_totals['BPG'] = player_data_totals['BLK'] / player_data_totals['GP']
player_data_totals['TOVPG'] = player_data_totals['TOV'] / player_data_totals['GP']
player_data_totals['MINPG'] = player_data_totals['MIN'] / player_data_totals['GP']
player_data_totals['OREBPG '] = player_data_totals['OREB'] / player_data_totals['GP']
player_data_totals['DREBPG'] = player_data_totals['DREB'] / player_data_totals['GP']
player_data_totals['STLPG   '] = player_data_totals['STL'] / player_data_totals['GP']
player_data_totals['BLKPG'] = player_data_totals['BLK'] / player_data_totals['GP']
player_data_totals['TOVPG'] = player_data_totals['TOV'] / player_data_totals['GP']
player_data_totals['PFPG'] = player_data_totals['PF'] / player_data_totals['GP']

In [65]:
# read to a csv
player_data_totals.to_csv('./data/nba_player_data_15_25.csv', index=False)